ABX-4225 Add name alias to mobile wallet list
KinesisNetwork/wallet-mobile pull request #3
Opened 2018-05-09 01:22 UTC by desnor

* update Wallet and Balance screen to provide input to
save and show account name property for each account
* update CreateAccount and WalletList to add new wallet to front of
wallet list instead of reversing in each render WalletList call

2018-05-09 06:57 UTC, Carl-Foster requested changes
Maybe just take out the async for some of them to save some overhead. Not a big deal but would clean it up a bit.

2018-05-09 06:57 UTC, Carl-Foster commented on src/services/wallet_persistance.ts
> +  const newWalletList = [walletEntry].concat(wallets)
But `[walletEntry, ...wallets]`

RESTY

2018-05-09 06:57 UTC, Carl-Foster commented on src/CreateAccount.tsx
> +let StellarBase = require('js-kinesis-sdk')
We should be importing this now since we have the types (I know it's just been moved)

2018-05-09 06:57 UTC, Carl-Foster commented on src/CreateAccount.tsx
> +  public setAlert = async ({ header, message }: { header: string , message: string }): Promise<boolean> => {
This doesn't look like it needs to be async, and neither does the validateCondition. Would be a bit cleaner without all the Promise.all

2018-05-10 01:13 UTC, desnor commented on src/services/wallet_persistance.ts
> +  const newWalletList = [walletEntry].concat(wallets)
:+1:

2018-05-10 01:19 UTC, desnor commented on src/CreateAccount.tsx
> +  public setAlert = async ({ header, message }: { header: string , message: string }): Promise<boolean> => {
I think I meant to call `await Alert.alert(....` as it previously seemed to wrap any Alert calls inside async functions. I don't know whether it's necessary, maybe it helps for dealing with the alert dismissal at that point. I'll look into it and take out the async if it doesn't make any difference to how it behaves.

2018-05-10 01:19 UTC, desnor commented on src/services/wallet_persistance.ts
> +  const newWalletList = [walletEntry].concat(wallets)
hang on ...SPREADY

2018-05-10 01:48 UTC, Carl-Foster commented on src/services/wallet_persistance.ts
> +  const newWalletList = [walletEntry].concat(wallets)
Oops true

2018-05-10 02:14 UTC, Carl-Foster approved these changes

2018-05-10 02:14 UTC, merged